name: deps build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Windows
      - name: Setup Env on Windows
        uses: microsoft/setup-msbuild@v1.1
      - name: Build on Windows
        working-directory: ${{ github.workspace }}
        run: |
            mkdir ${{ github.workspace }}/deps/build
            cd ${{ github.workspace }}/deps/build
            cmake ..
            cmake --build .
      - name: Package Deps on Windows
        working-directory: ${{ github.workspace }}
        run: |
            # Create zip file
            ls ${{ github.workspace }}
            ls ${{ github.workspace }}/deps
            ls ${{ github.workspace }}/deps/build
            $zipPath = "${{ github.workspace }}/deps/build/PrusaSlicer_deps_${{ env.date }}.zip"
            Compress-Archive -Path "${{ github.workspace }}/deps/build/destdir" -DestinationPath $zipPath
        shell: pwsh
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer_dep_win64_${{ env.date }}
          path: ${{ github.workspace }}/deps/build/PrusaSlicer_deps*.zip
