name: deps upload

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env on Windows
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore Deps Cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}\deps\build\destdir
          key: prusaslicer_deps_windows_2022

      - name: Package Deps
        working-directory: ${{ github.workspace }}
        run: |
            # Create zip file
            $date = Get-Date -Format "yyyyMMdd_HHmmss"
            $zipPath = "${{ github.workspace }}\deps\build\PrusaSlicer_deps_$date.zip"
            Compress-Archive -Path "${{ github.workspace }}\deps\build\destdir\user\local\*" -DestinationPath $zipPath
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer_deps_win64_${{ github.run_number }}
          path: ${{ github.workspace }}\build\PrusaSlicer_deps_*.zip
          retention-days: 1
