name: windows build

on:
  workflow_dispatch: {}
  push:
    branches:
      - xj-main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env on Windows
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup MSVC Dev Cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set Version and Date
        run: |
          # Get Date
          $date = Get-Date -Format "yyyyMMdd_HHmmss"

          # Extract version info
          $fileContent = Get-Content -Path "version.inc"
          $pattern = 'set\(SLIC3R_VERSION "([^"]+)"\)'
          $match = $fileContent | Select-String -Pattern $pattern -AllMatches
          $version = $match.Matches[0].Groups[1].Value

          echo "PS_VERSION=$version" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "PS_DATE=$date" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      - name: Restore Deps Cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/deps/build/destdir
          key: prusaslicer_deps_windows_2022

      - name: Build Deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}
        run: |
          mkdir ${{ github.workspace }}\deps\build
          cd ${{ github.workspace }}\deps\build
          cmake ..
          cmake --build . -j2

      - name: Save Deps Cache
        id: cache-deps-save
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}\deps\build\destdir
          key: prusaslicer_deps_windows_2022

      # - name: Package Deps
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #       # Create zip file
      #       ls ${{ github.workspace }}\deps\build\destdir\usr\local
      #       $date = Get-Date -Format "yyyyMMdd_HHmmss"
      #       $zipPath = "${{ github.workspace }}\deps\build\PrusaSlicer_deps_$date.zip"
      #       Compress-Archive -Path "${{ github.workspace }}\deps\build\destdir\usr\local" -DestinationPath $zipPath
      #   shell: pwsh

      # - name: Upload Deps Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: PrusaSlicer_deps_win64_${{ github.run_number }}
      #     path: ${{ github.workspace }}\deps\build\PrusaSlicer_deps_*
      #     retention-days: 1

      - name: Build Slicer
        working-directory: ${{ github.workspace }}
        run: |
          # make build dir
          mkdir ${{ github.workspace }}\build
          cd ${{ github.workspace }}\build

          # build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ github.workspace }}\deps\build\destdir\usr\local" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\build\destdir"
          cmake --build . -j2 --config Release

          # debug
          dir ${{ github.workspace }}\build\src\Release

          # Remove unwanted
          Remove-Item ${{ github.workspace }}\build\src\Release\*.lib
          Remove-Item ${{ github.workspace }}\build\src\Release\*.pdb
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer_${{ env.PS_VERSION }}_win64_${{ env.PS_DATE }}
          path: ${{ github.workspace }}\build\src\Release\*
          retention-days: 1
